### ISSUE TITLE
blog item on Debrief 173 Apr 8

### ISSUE THREAD

**Issue by dckc** [rchain/www#120]
Greg gave a great overview

 - [Debrief 173](https://www.youtube.com/watch?v=6Jfo2JLM6us&feature=youtu.be&t=713) at about 12min in

Darryl and James agreed Apr 21 to do this; Max agreed Apr 28 to help. ref

 - [RChain Communications Working Group Log](https://docs.google.com/document/d/1yrCqj5GWKElRVGYrPcrRDOEAZl4ILk3RYv00GFo6Yts/edit#heading=h.akytycdci9r8)

**Comment by MaximilianR** [comment]
Posted this in the Colab #Marketing channel before, putting it here for reference:

> In this Community Debrief, Greg Meredith discusses:
> 
> - How database technology has advanced over the last decades
> - What’s missing in current NoSQL approaches to data management
> - How RChain provides a solution to the missing parts of current NoSQL approaches, through Rholang, a programming language that provides clear query semantics and clear transactional semantics while maintaining the scalability of a NoSQL data store
> - Why you would want a blockchain-based storage solution in the first place
> - How hardware-acceleration can further increase the scalability of RChain
> - How quantum computing is a potential future technology that can be incorporated in leader-based consensus algorithms
> - Why any digital asset management solution need to be built on a scalable storage solution
> - How to scale to FaceBook-level transactional amounts

I did it in this way for now since I don't understand the technical things enough to do a direct summary. Would be great if some feedback could be given @dckc.

The [prospectus](https://drive.google.com/file/d/1g39bt78K4hVjsfG6dEXUJE2_g3MDqY1L/view) is meant to give a summary of RChain but it is too long to be handed out when people ask questions about RChain. The [RChain architecture page](https://architecture-docs.readthedocs.io/index.html) is also a possible reference but it is too technical (and somewhat out of date) to be given to laymen.

**Comment by dckc** [comment]
> Would be great if some feedback could be given @dckc.

ok...

> > In this Community Debrief, Greg Meredith discusses:

Let's be sure there's a link:

 In [Community Debrief 173](https://www.youtube.com/watch?v=6Jfo2JLM6us&feature=youtu.be&t=713), ...

**critical**

> I did it in this way for now since I don't understand the technical things enough to do a direct summary.

Works for me.

> The [prospectus](https://drive.google.com/file/d/1g39bt78K4hVjsfG6dEXUJE2_g3MDqY1L/view) is meant to give a summary of RChain but it is too long to be handed out when people ask questions about RChain.

"handed out"? Given a sufficiently contextualized link, readers can decide for themselves how much to read, yes?

> The [RChain architecture page](https://architecture-docs.readthedocs.io/index.html) is also a possible reference but it is too technical (and somewhat out of date) to be given to laymen.

Again, a link can give context: "Further technical discussion is available in the _RChain Platform Architecture_, though many of the details have been superceded by _actual development_."

But nothing says this blog item has to link to either of those. In due course, they should be easy enough to find.

@JamesMoc , would you please put this copy into a draft blog item? Has Darryl N. flipped whatever switches are involved to allow you to do that?

**Comment by JamesMoc** [comment]
@dckc 
Darryl hasn't gotten back to me yet.

**Comment by OPNO** [comment]
Hey guys - working on an edit from that debrief now. Gonna head to sleep soon though. TTY tomorrow......

**Comment by dckc** [comment]
this turned into quite a thing: https://blog.rchain.coop/blog/2020/05/15/mainnet-and-beyond/
